### ISSUE TITLE
General Project Questions/Feedback

### ISSUE THREAD

**Issue by SeriousBuds** [drolsen/DRO-Matic#43]
First of all let me start by saying a big heartfelt thanks for starting this project. This project is going to help not only hobby cannabis growers, but patients that can't truly can't afford their medication anymore. This could be built out to support the hobby agriculturist, or anyone that simply can't afford a vastly overpriced commercial dosing system.YOU'RE DOING GOD'S WORK, SON.

I hope to see you build a lot of functionality out of this! It would be awesome to see this take off.

**Questions**:
1. Do you know of any other detailed guides I can follow for the dosing mechanism, that will interface perfectly with your project? I do not have the time or craftsmanship to do a huge array of syringes. I think this is the most important because it's the largest barrier towards general public adoption to your project. 
2. Could I make a a [water solenoid valve](https://www.adafruit.com/products/997) work in a gravity fed solution, instead of the peristaltic pump alternative?
3. Would [this cheapo autodosing pump](http://www.ebay.com/itm/FREE-SHIP-Aquarium-Jebao-DP3-Auto-Dosing-Pump-3-Pumpheads-Doser-100-240V-ZVQU298-/381331059580) work in your system?
4. Will you add "real time" nutrient dosing/PH adjustment? From a farmer's perspective, I would argue this is easily the most important feature to implement into this project. You could have the probes constantly polling PH and PPM data and then dosing based on when those levels vary out of range over a set period of time (with a delay after dosing before retesting we can avoid the false positive of having the system dose PH/PPM to adjust and then immediately re-detecting a PH/PPM spike which we just administered).
   Does the project do this or do you intend to add this functionality? I think it's mission critical.

I'll send you a picture of the monsters I grow if you can add this functionality.

**Comment by drolsen** [comment]
Thanks! That means a lot to me!
Please be advise this code is not completed yet, as in this is still alpha phase. I'v just received a few more parts for me to finish the programming up this weekend (fingers crossed), so it wont actually dose until I get that part finished up.

1) My doser is crazy pants I know this, and most will never build one to my specs and if they do huge props. So I'm planning on putting together another video of me build a doser out of http://tinyurl.com/jrf24ny these pumps. They are much cheaper, easy to mount and yes I'm planing to make my OS work with these as well. The big difference between the two is how the calibration is done, syringes need to be configured to a fixed size, and then calibrate how many rotations it takes to reach fixed size. Peristaltic pumps however you would set size to infinite, and no need to calibrate rotations (infact option will be gone from menus if set to infinite). From here all normal functionality of OS works the same.

2) Taking a quick look at these, I don't see why not. Each would be a channel technique and you would configure them as I've mentioned above for peristaltic pumps, but I don't know if gravity is strong enough to open that valve.. I just don't know about these yet, but thank you I'm now very interested :) 

3) I honestly don't know, and would have to lean on the side of no, cause they have their own OS (mind you far less features) baked into the box. I don't know without opening it if you could install the OS on this and/or replace hardware with micro controller to use pumps. (I NEED TEST FUNDS hehe)

4) My plan is to use two Arduino ready PPM/PH readers for dosed water and runoff water; if OS configured to do so, it will adjust the dose numbers based on a comparison of before and after results. Its a ways out for sure, as I've only focused on the dosed water reading portion for the basic OS functionality so far.  But we will get there soon enough. 

To be clear, the only thing the OS will do once feature is done, is lower/raise all channels solutions dosed amounts by X% in respond to say runoff water still containing a very high/low PPM. Not be real-time adjustments, but rather dosing schedule adjustment to either PPM or PH.

In the future I would like to have real-time adjustments based on the runoff probe, but baby steps, and dang-it I need more money hehe.
